name: Receive SHA
run-name: Running Receive SHA attempt ${{ github.run_number }}

on:
  workflow_run:
    workflows: ["Save SHA"]
    types:
      - completed

jobs:
  deploy_to_test:
    name: Deploy To Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Echo workflow_run head SHA
        run: echo "workflow_run head SHA ${{ github.event.workflow_run.head_sha }}"
      - name: Echo github SHA
        run: echo "github branch SHA ${{ github.SHA }}"
      - name: Echo workflow id
        run: echo "github parent workflow id ${{ github.event.workflow_run.id }}"
      - name: Download commit SHA from Save SHA
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
          name: sha
          run-id: ${{ github.event.workflow_run.id }}
      - name: Read SHA into environment
        id: read-sha
        run: echo "SHA=$(cat sha.txt)" >> $GITHUB_ENV
      - name: Re-upload commit SHA for downstream workflows
        uses: actions/upload-artifact@v4
        with:
          name: sha
          path: sha.txt
      - name: Echo env SHA
        run: echo "github env SHA ${{ env.SHA }}"
