name: Finish SHA
run-name: Running Finish SHA attempt ${{ github.run_number }}

permissions:
  actions: read
  contents: read

on:
  workflow_run:
    workflows: ["Receive SHA"]
    types:
      - completed

jobs:
  deploy_to_test:
    permissions:
      actions: read
    name: Deploy To Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Echo workflow_run head SHA
        run: echo "workflow_run head SHA ${{ github.event.workflow_run.head_sha }}"
      - name: Echo github SHA
        run: echo "github branch SHA ${{ github.SHA }}"

      - name: Download commit SHA from Save SHA
        uses: actions/download-artifact@v3
        with:
          github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
          name: sha
      - name: Read SHA into environment
        run: echo "SHA=$(cat sha.txt)" >> $GITHUB_ENV
      - name: Re-upload commit SHA for downstream workflows
        uses: actions/upload-artifact@v3
        with:
          name: sha
          path: sha.txt
