name: Save SHA
run-name: Save SHA Attempt ${{ github.run_number }}

on: push

jobs:
  save_sha:
    name: Build Helm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false # Disable submodules to avoid the dbgorilla_mcp issue
      - name: Echo workflow_run head SHA
        run: echo "workflow_run head SHA ${{ github.event.workflow_run.head_sha }}"
      - name: Echo github SHA
        run: echo "github branch SHA ${{ github.SHA }}"
      - name: Save commit SHA
        run: echo "${{ github.sha }}" > sha.txt
      - name: Upload commit SHA artifact
        uses: actions/upload-artifact@v3
        with:
          name: sha
          path: sha.txt
