name: CI Integration Tests
run-name: Running CI Integration Tests ${{ github.run_number }}

on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed

jobs:
  deploy_to_test:
    name: Deploy To Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download commit SHA from CI Build
        uses: actions/download-artifact@v4
        with:
          name: sha
      - name: Read SHA into environment
        id: read-sha
        run: echo "SHA=$(cat commit-sha.txt)" >> $GITHUB_ENV
      - name: Re-upload commit SHA for downstream workflows
        uses: actions/upload-artifact@v4
        with:
          name: sha
          path: commit-sha.txt
