name: Finish SHA
run-name: Running Finish SHA attempt ${{ github.run_number }}
#do something
on:
  workflow_run:
    workflows: ["Receive SHA"]
    types:
      - completed

jobs:
  deploy_to_test:
    name: Deploy To Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Echo workflow_run head SHA
        run: echo "workflow_run head SHA ${{ github.event.workflow_run.head_sha }}"
      - name: Echo github SHA
        run: echo "github branch SHA ${{ github.SHA }}"
