name: Download Artifact

on:
  workflow_run:
    workflows: ["Build and Upload Artifact"]

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-build-artifact
          path: downloaded_artifacts
      - name: Verify downloaded content
        run: cat downloaded_artifacts/my_artifact.txt